[project]
name = "ml-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib==3.10.8",
    "numpy==2.4.2",
    "pytest==9.0.2",
    "scikit-learn>=1.8.0",
]
